// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAok2uFq5qDdjGRyCMQ4TAdZMGC5xm_kKY',
    appId: '1:682411584478:web:f4f1548398e70941968b4f',
    messagingSenderId: '682411584478',
    projectId: 'appgame-ccca4',
    authDomain: 'appgame-ccca4.firebaseapp.com',
    storageBucket: 'appgame-ccca4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Pux50UVE0tqmUYAlmDxGgle4iBGj8aE',
    appId: '1:682411584478:android:7da9c24745d2011e968b4f',
    messagingSenderId: '682411584478',
    projectId: 'appgame-ccca4',
    storageBucket: 'appgame-ccca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUVKfPOvoRGbcDg12_Yp_w1MfB_tN80k',
    appId: '1:682411584478:ios:0edf4a0cd06371c2968b4f',
    messagingSenderId: '682411584478',
    projectId: 'appgame-ccca4',
    storageBucket: 'appgame-ccca4.firebasestorage.app',
    iosBundleId: 'com.example.appgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUVKfPOvoRGbcDg12_Yp_w1MfB_tN80k',
    appId: '1:682411584478:ios:0edf4a0cd06371c2968b4f',
    messagingSenderId: '682411584478',
    projectId: 'appgame-ccca4',
    storageBucket: 'appgame-ccca4.firebasestorage.app',
    iosBundleId: 'com.example.appgame',
  );

}